# Generated by Django 5.2.1 on 2025-06-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichajeRemoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='horas',
            field=models.SmallIntegerField(default=0, verbose_name='horas'),
        ),
    ]
