# Generated by Django 5.2.1 on 2025-06-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichajeRemoto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='empresa_timeOffset',
            field=models.SmallIntegerField(default=0, verbose_name='adjuste horario'),
        ),
        migrations.AlterField(
            model_name='tecladofichaje',
            name='empresa_timeOffset',
            field=models.SmallIntegerField(default=0, verbose_name='adjuste horario'),
        ),
    ]
