# Generated by Django 5.2.1 on 2025-06-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichajeRemoto', '0002_registro_horas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='horas',
        ),
        migrations.AddField(
            model_name='registro',
            name='minutos',
            field=models.SmallIntegerField(default=0, verbose_name='minutos'),
        ),
    ]
