# Generated by Django 5.2.1 on 2025-06-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichajeRemoto', '0004_registro_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_working',
            field=models.BooleanField(default=False, verbose_name='trabajando ahora mismo'),
        ),
    ]
