# Generated by Django 5.2.1 on 2025-06-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichajeRemoto', '0003_tecladofichaje_lastupdate'),
        ('fichajeRemoto', '0005_usuario_is_working'),
    ]

    operations = [
    ]
