# Generated by Django 5.2.1 on 2025-06-17 15:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresaCodigo', models.IntegerField()),
                ('empresaNombre', models.CharField(max_length=200)),
                ('empresa_timeOffset', models.SmallIntegerField(default=0, verbose_name='adjuste horario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioNombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('usuarioApellido', models.CharField(max_length=200, verbose_name='Apellido ')),
                ('usuarioDNI', models.CharField(default='', max_length=9, verbose_name='DNI')),
                ('usuarioPIN', models.SmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='PIN')),
            ],
        ),
        migrations.CreateModel(
            name='TecladoFichaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAC_address', models.CharField(default='00:00:00:00:00:00', max_length=17)),
                ('empresa_timeOffset', models.SmallIntegerField(default=0, verbose_name='adjuste horario')),
                ('IsActive', models.BooleanField(default=True)),
                ('lastUpdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa_asociada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fichajeRemoto.empresa', verbose_name='Empresa asociada')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regEntrada', models.DateTimeField(verbose_name='Entrada')),
                ('regSalida', models.DateTimeField(blank=True, null=True, verbose_name='Salida')),
                ('teclado_asocido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fichajeRemoto.tecladofichaje', verbose_name='Lugar')),
                ('regUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichajeRemoto.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
