# Generated by Django 5.2.1 on 2025-06-04 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichajeRemoto', '0002_alter_empresa_empresa_timeoffset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecladofichaje',
            name='lastUpdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
