# Generated by Django 5.2.1 on 2025-06-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichajeRemoto', '0003_remove_registro_horas_registro_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='horas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='horas'),
        ),
    ]
