"""
Django settings for controlFichaje_backEnd project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
PROJECT_DIR=os.path.dirname(__file__)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vs32uoax*yjq+uw(!&t)e=4%!1om#x%9w^^kk52q$e4$-3ewpm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    #'corsheaders',

    'core',
    'fichajeRemoto',

    'pwa',  # MODO  Progressive Web Apps (PWAs):
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'controlFichaje_backEnd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


'''
Opción 2: Usar un directorio global de plantillas compartidas
Si deseas tener un lugar central para HTMLs comunes (como base.html), puedes hacer:

templates/
├── base.html
├── login.html
Y en settings.py:

python
Copiar
Editar
'DIRS': [os.path.join(BASE_DIR, 'templates')],
'APP_DIRS': True,
Esto te permite usar plantillas sin depender de una app específica.
'''

WSGI_APPLICATION = 'controlFichaje_backEnd.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

'''
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
'''

LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'Europe/Madrid'  
USE_I18N = True
USE_L10N = True
USE_TZ = True

APPEND_SLASH = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


#STATIC_ROOT= os.path.join(PROJECT_DIR,'static_media/')

#STATIC_URL = 'static/'


STATIC_URL = 'static/'
STATIC_ROOT=os.path.join(BASE_DIR, 'static/') 

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Para desarrollo
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'fichajeRemoto/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




PWA_APP_NAME = 'Fichaje Remoto'
PWA_APP_DESCRIPTION = "Acceso móvil al sistema de fichaje remoto"
PWA_APP_THEME_COLOR = '#ffffff'
PWA_APP_BACKGROUND_COLOR = '#f8f9fa'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/fichajeRemoto/'
PWA_APP_START_URL = '/fichajeRemoto/'  # Debe coincidir con tu URL de acceso
PWA_APP_ICONS = [
    {
        'src': '/static/fichajeRemoto/pwa_icons/icon-128x128.png',   #'/static/icons/icon-192x192.png',
        'sizes': '128x128'
    },
   # {
   #     'src': '/static/fichajeRemoto/pwa_icons/icon-192x192.png',   #'/static/icons/icon-192x192.png',
   #     'sizes': '192x192'
   # },
    {
        'src': '/static/fichajeRemoto/pwa_icons/icon-512x512.png',   #'/static/icons/icon-512x512.png',
        'sizes': '512x512'
    }
]
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static/js', 'serviceworker.js')

